foreground   #e9e5e4
background   #1d1616
cursor       #e9e5e4

color0       #1d1616
color8       #a3a09f
color1       #D18E73
color9       #D18E73
color2       #897E81
color10      #897E81
color3       #A79F9F
color11      #A79F9F
color4       #D6B3A6
color12      #D6B3A6
color5       #D3C4BA
color13      #D3C4BA
color6       #D5CECE
color14      #D5CECE
color7       #e9e5e4
color15      #e9e5e4
