# ╔════════════════════════════════════════════╗
# ║       🌫️  EFECTOS GLOBALES (BLUR/OPACIDAD) ║
# ╚════════════════════════════════════════════╝
decoration {
    rounding = 8

    blur {
        enabled = true
        size = 8
        passes = 2
        new_optimizations = true
        ignore_opacity = false
        xray = false
    }

    active_opacity = 0.9
    inactive_opacity = 0.8
    fullscreen_opacity = 1.0
}

# Blur para TODAS las capas (Rofi, notificaciones, control center, etc.)
# layerrule = blur on, match:namespace waybar


# ╔════════════════════════════════════════════╗
# ║         💤  INHIBICIÓN DE INACTIVIDAD       ║
# ╚════════════════════════════════════════════╝
windowrule = idle_inhibit fullscreen, match:class ^(.*celluloid.*|.*mpv.*|.*vlc.*)$
windowrule = idle_inhibit fullscreen, match:class ^(.*[Ss]potify.*)$
windowrule = idle_inhibit fullscreen, match:class ^(.*LibreWolf.*|.*floorp.*|.*brave-browser.*|.*firefox.*|.*chromium.*|.*zen.*|.*vivaldi.*)$

# ╔════════════════════════════════════════════╗
# ║         📺  PICTURE-IN-PICTURE SETTINGS     ║
# ╚════════════════════════════════════════════╝
windowrule = tag +picture-in-picture, match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture).*$
windowrule = float on, match:tag picture-in-picture
windowrule = keep_aspect_ratio on, match:tag picture-in-picture
windowrule = move (monitor_w*0.73) (monitor_h*0.72), match:tag picture-in-picture
#windowrule = size (monitor_w*0.25) (monitor_h*0.25), match:tag picture-in-picture
windowrule = pin on, match:tag picture-in-picture

# ╔════════════════════════════════════════════╗
# ║              🪟  VENTANAS FLOTANTES          ║
# ╚════════════════════════════════════════════╝
windowrule = float on, match:class ^(Signal)$
windowrule = float on, match:class ^(com.github.rafostar.Clapper)$
windowrule = float on, match:class ^(app.drey.Warp)$
windowrule = float on, match:class ^(net.davidotek.pupgui2)$
windowrule = float on, match:class ^(yad)$
windowrule = float on, match:class ^(eog)$
windowrule = float on, match:class ^(io.github.alainm23.planify)$
windowrule = float on, match:class ^(io.gitlab.theevilskeleton.Upscaler)$
windowrule = float on, match:class ^(com.github.unrud.VideoDownloader)$
windowrule = float on, match:class ^(io.gitlab.adhami3310.Impression)$
windowrule = float on, match:class ^(io.missioncenter.MissionCenter)$