foreground   #ddcfd8
background   #2e2328
cursor       #ddcfd8

color0       #2e2328
color8       #9a9097
color1       #A85DAF
color9       #A85DAF
color2       #E55F9C
color10      #E55F9C
color3       #758E97
color11      #758E97
color4       #49D1D3
color12      #49D1D3
color5       #9C9BA6
color13      #9C9BA6
color6       #D397AB
color14      #D397AB
color7       #ddcfd8
color15      #ddcfd8
