foreground         #c3c7c9
background         #12212a
background_opacity 1.0
cursor             #c3c7c9

active_tab_foreground     #12212a
active_tab_background     #c3c7c9
inactive_tab_foreground   #c3c7c9
inactive_tab_background   #12212a

active_border_color   #c3c7c9
inactive_border_color #12212a
bell_border_color     #0d5771

color0       #12212a
color8       #616e76
color1       #0d5771
color9       #127497
color2       #116a84
color10      #178EB1
color3       #12787b
color11      #18A1A4
color4       #398e84
color12      #4DBEB0
color5       #209387
color13      #2BC5B5
color6       #167e9c
color14      #1EA9D0
color7       #949a9e
color15      #c3c7c9
