[colors.primary]
background = "#15060f"
foreground = "#efcacc"

[colors.cursor]
text = "#15060f"
cursor = "#efcacc"

[colors.normal]
black   = "#15060f"
red     = "#A7596A"
green   = "#CC6975"
yellow  = "#BD7682"
blue    = "#D07885"
magenta = "#D7898F"
cyan    = "#E99296"
white   = "#efcacc"

[colors.bright]
black   = "#a78d8e"
red     = "#A7596A"
green   = "#CC6975"
yellow  = "#BD7682"
blue    = "#D07885"
magenta = "#D7898F"
cyan    = "#E99296"
white   = "#efcacc"
