[colors.primary]
background = "#0b0b1a"
foreground = "#d6d7e0"

[colors.cursor]
text = "#0b0b1a"
cursor = "#d6d7e0"

[colors.normal]
black   = "#0b0b1a"
red     = "#9E629F"
green   = "#E07197"
yellow  = "#BA69CA"
blue    = "#539BB9"
magenta = "#F3969D"
cyan    = "#EE9EE0"
white   = "#d6d7e0"

[colors.bright]
black   = "#95969c"
red     = "#9E629F"
green   = "#E07197"
yellow  = "#BA69CA"
blue    = "#539BB9"
magenta = "#F3969D"
cyan    = "#EE9EE0"
white   = "#d6d7e0"

[font]
size = 7.5

[font.normal]
family = "MesloLGS NF"
