foreground   #d6d7e0
background   #0b0b1a
cursor       #d6d7e0

color0       #0b0b1a
color8       #95969c
color1       #9E629F
color9       #9E629F
color2       #E07197
color10      #E07197
color3       #BA69CA
color11      #BA69CA
color4       #539BB9
color12      #539BB9
color5       #F3969D
color13      #F3969D
color6       #EE9EE0
color14      #EE9EE0
color7       #d6d7e0
color15      #d6d7e0
