[colors.primary]
background = "#161831"
foreground = "#e4e1e9"

[colors.cursor]
text = "#161831"
cursor = "#e4e1e9"

[colors.normal]
black   = "#161831"
red     = "#9290B4"
green   = "#AB97AE"
yellow  = "#DCAAB1"
blue    = "#B0ABC8"
magenta = "#CEBACC"
cyan    = "#C1C1D3"
white   = "#e4e1e9"

[colors.bright]
black   = "#9f9da3"
red     = "#9290B4"
green   = "#AB97AE"
yellow  = "#DCAAB1"
blue    = "#B0ABC8"
magenta = "#CEBACC"
cyan    = "#C1C1D3"
white   = "#e4e1e9"

[font.normal]
family = "MesloLGS NF"
