[colors.primary]
background = "#1c0912"
foreground = "#e9bfc8"

[colors.cursor]
text = "#1c0912"
cursor = "#e9bfc8"

[colors.normal]
black   = "#1c0912"
red     = "#AC5172"
green   = "#C65770"
yellow  = "#A89070"
blue    = "#B66789"
magenta = "#D0728D"
cyan    = "#CD66B8"
white   = "#e9bfc8"

[colors.bright]
black   = "#a3858c"
red     = "#AC5172"
green   = "#C65770"
yellow  = "#A89070"
blue    = "#B66789"
magenta = "#D0728D"
cyan    = "#CD66B8"
white   = "#e9bfc8"

[font.normal]
family = "MesloLGS NF"
