foreground   #efe0e0
background   #272131
cursor       #efe0e0

color0       #272131
color8       #a79c9c
color1       #B18F94
color9       #B18F94
color2       #AD9AA4
color10      #AD9AA4
color3       #DDA4A4
color11      #DDA4A4
color4       #D3ACAE
color12      #D3ACAE
color5       #F4C4B9
color13      #F4C4B9
color6       #C5B2C3
color14      #C5B2C3
color7       #efe0e0
color15      #efe0e0
