foreground   #8edce4
background   #031E2D
cursor       #8edce4

color0       #031E2D
color8       #639a9f
color1       #127497
color9       #127497
color2       #178EB1
color10      #178EB1
color3       #18A1A4
color11      #18A1A4
color4       #4DBEB0
color12      #4DBEB0
color5       #2BC5B5
color13      #2BC5B5
color6       #1EA9D0
color14      #1EA9D0
color7       #8edce4
color15      #8edce4
