[colors.primary]
background = "#0a1629"
foreground = "#c3ecf2"

[colors.cursor]
text = "#0a1629"
cursor = "#c3ecf2"

[colors.normal]
black   = "#0a1629"
red     = "#0469D0"
green   = "#19A2EB"
yellow  = "#51ACD4"
blue    = "#2FC8F7"
magenta = "#5DD6F7"
cyan    = "#CEADA8"
white   = "#c3ecf2"

[colors.bright]
black   = "#88a5a9"
red     = "#0469D0"
green   = "#19A2EB"
yellow  = "#51ACD4"
blue    = "#2FC8F7"
magenta = "#5DD6F7"
cyan    = "#CEADA8"
white   = "#c3ecf2"

[font.normal]
family = "MesloLGS NF"
