[colors.primary]
background = "#16212b"
foreground = "#c9dde7"

[colors.cursor]
text = "#16212b"
cursor = "#c9dde7"

[colors.normal]
black   = "#16212b"
red     = "#AD7193"
green   = "#648FAE"
yellow  = "#66A6CA"
blue    = "#9998AF"
magenta = "#99B4CC"
cyan    = "#E2A9C0"
white   = "#c9dde7"

[colors.bright]
black   = "#8c9aa1"
red     = "#AD7193"
green   = "#648FAE"
yellow  = "#66A6CA"
blue    = "#9998AF"
magenta = "#99B4CC"
cyan    = "#E2A9C0"
white   = "#c9dde7"

[font.normal]
family = "MesloLGS NF"
