foreground         #c5c3c8
background         #180f23
background_opacity 1.0
cursor             #c5c3c8

active_tab_foreground     #180f23
active_tab_background     #c5c3c8
inactive_tab_foreground   #c5c3c8
inactive_tab_background   #180f23

active_border_color   #c5c3c8
inactive_border_color #180f23
bell_border_color     #90556E

color0       #180f23
color8       #675e74
color1       #90556E
color9       #90556E
color2       #6C658F
color10      #6C658F
color3       #5E41A4
color11      #5E41A4
color4       #946F98
color12      #946F98
color5       #AB67B7
color13      #AB67B7
color6       #8D908A
color14      #8D908A
color7       #c5c3c8
color15      #c5c3c8
