[colors.primary]
background = "#030316"
foreground = "#ebcfc9"

[colors.cursor]
text = "#030316"
cursor = "#ebcfc9"

[colors.normal]
black   = "#030316"
red     = "#D21F5F"
green   = "#9E445F"
yellow  = "#7D7E80"
blue    = "#5F958C"
magenta = "#65A89C"
cyan    = "#B2BAAE"
white   = "#ebcfc9"

[colors.bright]
black   = "#a4908c"
red     = "#D21F5F"
green   = "#9E445F"
yellow  = "#7D7E80"
blue    = "#5F958C"
magenta = "#65A89C"
cyan    = "#B2BAAE"
white   = "#ebcfc9"

[font.normal]
family = "MesloLGS NF"
