foreground   #ebcfc9
background   #030316
cursor       #ebcfc9

color0       #030316
color8       #a4908c
color1       #D21F5F
color9       #D21F5F
color2       #9E445F
color10      #9E445F
color3       #7D7E80
color11      #7D7E80
color4       #5F958C
color12      #5F958C
color5       #65A89C
color13      #65A89C
color6       #B2BAAE
color14      #B2BAAE
color7       #ebcfc9
color15      #ebcfc9
