[colors.primary]
background = "#3d405a"
foreground = "#eae8ed"

[colors.cursor]
text = "#3d405a"
cursor = "#eae8ed"

[colors.normal]
black   = "#3d405a"
red     = "#CFB8D1"
green   = "#A4CBF3"
yellow  = "#CDCAD6"
blue    = "#F7D5D5"
magenta = "#D4D4ED"
cyan    = "#E3DCF1"
white   = "#eae8ed"

[colors.bright]
black   = "#a3a2a5"
red     = "#CFB8D1"
green   = "#A4CBF3"
yellow  = "#CDCAD6"
blue    = "#F7D5D5"
magenta = "#D4D4ED"
cyan    = "#E3DCF1"
white   = "#eae8ed"

[font]
size = 7.5

[font.normal]
family = "MesloLGS NF"
