[colors.primary]
background = "#031E2D"
foreground = "#8edce4"

[colors.cursor]
text = "#031E2D"
cursor = "#8edce4"

[colors.normal]
black   = "#031E2D"
red     = "#127497"
green   = "#178EB1"
yellow  = "#18A1A4"
blue    = "#4DBEB0"
magenta = "#2BC5B5"
cyan    = "#1EA9D0"
white   = "#8edce4"

[colors.bright]
black   = "#639a9f"
red     = "#127497"
green   = "#178EB1"
yellow  = "#18A1A4"
blue    = "#4DBEB0"
magenta = "#2BC5B5"
cyan    = "#1EA9D0"
white   = "#8edce4"

[font.normal]
family = "MesloLGS NF"
