foreground   #dbd1da
background   #0a030e
cursor       #dbd1da

color0       #0a030e
color8       #999298
color1       #B13836
color9       #B13836
color2       #D8CB45
color10      #D8CB45
color3       #703E95
color11      #703E95
color4       #9759AF
color12      #9759AF
color5       #AA61C9
color13      #AA61C9
color6       #7C89E1
color14      #7C89E1
color7       #dbd1da
color15      #dbd1da
