[colors.primary]
background = "#410e01"
foreground = "#f4f4df"

[colors.cursor]
text = "#410e01"
cursor = "#f4f4df"

[colors.normal]
black   = "#410e01"
red     = "#E79D2A"
green   = "#A79263"
yellow  = "#DFB152"
blue    = "#F3D760"
magenta = "#BEB08D"
cyan    = "#F2EDA1"
white   = "#f4f4df"

[colors.bright]
black   = "#aaaa9c"
red     = "#E79D2A"
green   = "#A79263"
yellow  = "#DFB152"
blue    = "#F3D760"
magenta = "#BEB08D"
cyan    = "#F2EDA1"
white   = "#f4f4df"

[font.normal]
family = "MesloLGS NF"
