[colors.primary]
background = "#0f1017"
foreground = "#dbeaf6"

[colors.cursor]
text = "#0f1017"
cursor = "#dbeaf6"

[colors.normal]
black   = "#0f1017"
red     = "#29A9F6"
green   = "#65A1D5"
yellow  = "#B6A7AC"
blue    = "#9AC4FE"
magenta = "#A4D4FF"
cyan    = "#BCDFFC"
white   = "#dbeaf6"

[colors.bright]
black   = "#99a3ac"
red     = "#29A9F6"
green   = "#65A1D5"
yellow  = "#B6A7AC"
blue    = "#9AC4FE"
magenta = "#A4D4FF"
cyan    = "#BCDFFC"
white   = "#dbeaf6"

[font.normal]
family = "MesloLGS NF"
