[colors.primary]
background = "#3B4252"
foreground = "#ECEFF4"

[colors.cursor]
text = "#3B4252"
cursor = "#ECEFF4"

[colors.normal]
black   = "#3B4252"
red     = "#BF616A"
green   = "#A3BE8C"
yellow  = "#EBCB8B"
blue    = "#81A1C1"
magenta = "#B48EAD"
cyan    = "#88C0D0"
white   = "#E5E9F0"

[colors.bright]
black   = "#4C566A"
red     = "#BF616A"
green   = "#A3BE8C"
yellow  = "#EBCB8B"
blue    = "#81A1C1"
magenta = "#B48EAD"
cyan    = "#8FBCBB"
white   = "#ECEFF4"

[font]
size = 7.5

[font.normal]
family = "MesloLGS NF"
