[colors.primary]
background = "#010101"
foreground = "#e6e6e7"

[colors.cursor]
text = "#010101"
cursor = "#e6e6e7"

[colors.normal]
black   = "#010101"
red     = "#52DEC8"
green   = "#909090"
yellow  = "#9F9EA0"
blue    = "#B1B1B1"
magenta = "#C0BFC0"
cyan    = "#CACACA"
white   = "#e6e6e7"

[colors.bright]
black   = "#a1a1a1"
red     = "#52DEC8"
green   = "#909090"
yellow  = "#9F9EA0"
blue    = "#B1B1B1"
magenta = "#C0BFC0"
cyan    = "#CACACA"
white   = "#e6e6e7"

[font.normal]
family = "MesloLGS NF"
