[colors.primary]
background = "#120f17"
foreground = "#c7bfcc"

[colors.cursor]
text = "#120f17"
cursor = "#c7bfcc"

[colors.normal]
black   = "#120f17"
red     = "#90556E"
green   = "#6C658F"
yellow  = "#5E41A4"
blue    = "#946F98"
magenta = "#AB67B7"
cyan    = "#8D908A"
white   = "#c7bfcc"

[colors.bright]
black   = "#8b858e"
red     = "#90556E"
green   = "#6C658F"
yellow  = "#5E41A4"
blue    = "#946F98"
magenta = "#AB67B7"
cyan    = "#8D908A"
white   = "#c7bfcc"

[font.normal]
family = "MesloLGS NF"
