[colors.primary]
background = "#131139"
foreground = "#e4d3cb"

[colors.cursor]
text = "#131139"
cursor = "#e4d3cb"

[colors.normal]
black   = "#131139"
red     = "#5D75C4"
green   = "#AD3385"
yellow  = "#9F73A1"
blue    = "#DC6F90"
magenta = "#AC909E"
cyan    = "#E6969A"
white   = "#e4d3cb"

[colors.bright]
black   = "#9f938e"
red     = "#5D75C4"
green   = "#AD3385"
yellow  = "#9F73A1"
blue    = "#DC6F90"
magenta = "#AC909E"
cyan    = "#E6969A"
white   = "#e4d3cb"

[font]
size = 7.5

[font.normal]
family = "MesloLGS NF"
