foreground   #e4d3cb
background   #131139
cursor       #e4d3cb

color0       #131139
color8       #9f938e
color1       #5D75C4
color9       #5D75C4
color2       #AD3385
color10      #AD3385
color3       #9F73A1
color11      #9F73A1
color4       #DC6F90
color12      #DC6F90
color5       #AC909E
color13      #AC909E
color6       #E6969A
color14      #E6969A
color7       #e4d3cb
color15      #e4d3cb
