[colors.primary]
background = "#1b1312"
foreground = "#f2ecdf"

[colors.cursor]
text = "#1b1312"
cursor = "#f2ecdf"

[colors.normal]
black   = "#1b1312"
red     = "#D3A162"
green   = "#69758D"
yellow  = "#ACA196"
blue    = "#D4B590"
magenta = "#E9D2A8"
cyan    = "#E1D9CD"
white   = "#f2ecdf"

[colors.bright]
black   = "#a9a59c"
red     = "#D3A162"
green   = "#69758D"
yellow  = "#ACA196"
blue    = "#D4B590"
magenta = "#E9D2A8"
cyan    = "#E1D9CD"
white   = "#f2ecdf"

[font.normal]
family = "MesloLGS NF"
