[colors.primary]
background = "#232510"
foreground = "#dfe0e6"

[colors.cursor]
text = "#232510"
cursor = "#dfe0e6"

[colors.normal]
black   = "#232510"
red     = "#1165B5"
green   = "#0374C4"
yellow  = "#3A93C4"
blue    = "#5AA5D1"
magenta = "#ADB5B9"
cyan    = "#A5B4CB"
white   = "#dfe0e6"

[colors.bright]
black   = "#9c9ca1"
red     = "#1165B5"
green   = "#0374C4"
yellow  = "#3A93C4"
blue    = "#5AA5D1"
magenta = "#ADB5B9"
cyan    = "#A5B4CB"
white   = "#dfe0e6"

[font.normal]
family = "MesloLGS NF"
