[Desktop Entry]
Type=X-GNOME-Metatheme
Name=my-wal-theme-ruby
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=my-wal-theme-ruby
GtkTheme=my-wal-theme-ruby
IconTheme=my-wal-theme-ruby
MetacityTheme=my-wal-theme-ruby
