[colors.primary]
background = "#251f29"
foreground = "#f0ece2"

[colors.cursor]
text = "#251f29"
cursor = "#f0ece2"

[colors.normal]
black   = "#251f29"
red     = "#A99C9D"
green   = "#CEAAA8"
yellow  = "#DED2AD"
blue    = "#AFAACB"
magenta = "#DCAAD0"
cyan    = "#E8D2D9"
white   = "#f0ece2"

[colors.bright]
black   = "#a8a59e"
red     = "#A99C9D"
green   = "#CEAAA8"
yellow  = "#DED2AD"
blue    = "#AFAACB"
magenta = "#DCAAD0"
cyan    = "#E8D2D9"
white   = "#f0ece2"

[font.normal]
family = "MesloLGS NF"
