[colors.primary]
background = "#242b36"
foreground = "#eff0f0"

[colors.cursor]
text = "#242b36"
cursor = "#eff0f0"

[colors.normal]
black   = "#242b36"
red     = "#8D99A8"
green   = "#A6BAC6"
yellow  = "#D5BCC3"
blue    = "#C9D2DD"
magenta = "#E9D6DE"
cyan    = "#D1D9E2"
white   = "#eff0f0"

[colors.bright]
black   = "#a7a8a8"
red     = "#8D99A8"
green   = "#A6BAC6"
yellow  = "#D5BCC3"
blue    = "#C9D2DD"
magenta = "#E9D6DE"
cyan    = "#D1D9E2"
white   = "#eff0f0"

[font.normal]
family = "MesloLGS NF"
