foreground   #80f1f1
background   #080A0A
cursor       #80f1f1

color0       #080A0A
color8       #59a8a8
color1       #CB4757
color9       #CB4757
color2       #4D7B83
color10      #4D7B83
color3       #168F90
color11      #168F90
color4       #1CA7A8
color12      #1CA7A8
color5       #54B9BE
color13      #54B9BE
color6       #1FD8DA
color14      #1FD8DA
color7       #80f1f1
color15      #80f1f1
