foreground   #f4ece4
background   #2d2325
cursor       #f4ece4

color0       #2d2325
color8       #aaa59f
color1       #AE9699
color9       #AE9699
color2       #D49FA4
color10      #D49FA4
color3       #E7B0B1
color11      #E7B0B1
color4       #E8BEC1
color12      #E8BEC1
color5       #DBD0D4
color13      #DBD0D4
color6       #F5D2CF
color14      #F5D2CF
color7       #f4ece4
color15      #f4ece4
