[colors.primary]
background = "#1f1011"
foreground = "#ddd3da"

[colors.cursor]
text = "#1f1011"
cursor = "#ddd3da"

[colors.normal]
black   = "#1f1011"
red     = "#93698C"
green   = "#CD6388"
yellow  = "#AE93A4"
blue    = "#D5ACA8"
magenta = "#EDCEB6"
cyan    = "#B5B1C7"
white   = "#ddd3da"

[colors.bright]
black   = "#9a9398"
red     = "#93698C"
green   = "#CD6388"
yellow  = "#AE93A4"
blue    = "#D5ACA8"
magenta = "#EDCEB6"
cyan    = "#B5B1C7"
white   = "#ddd3da"

[font.normal]
family = "MesloLGS NF"
