[colors.primary]
background = "#0f0c0c"
foreground = "#f6e9e1"

[colors.cursor]
text = "#0f0c0c"
cursor = "#f6e9e1"

[colors.normal]
black   = "#0f0c0c"
red     = "#3E54AB"
green   = "#E3AF9D"
yellow  = "#C4B1B0"
blue    = "#FEBDAD"
magenta = "#D0CDD1"
cyan    = "#FBDCCD"
white   = "#f6e9e1"

[colors.bright]
black   = "#aca39d"
red     = "#3E54AB"
green   = "#E3AF9D"
yellow  = "#C4B1B0"
blue    = "#FEBDAD"
magenta = "#D0CDD1"
cyan    = "#FBDCCD"
white   = "#f6e9e1"

[font.normal]
family = "MesloLGS NF"
