[colors.primary]
background = "#1c1a3d"
foreground = "#d6d9e3"

[colors.cursor]
text = "#1c1a3d"
cursor = "#d6d9e3"

[colors.normal]
black   = "#1c1a3d"
red     = "#7E80B6"
green   = "#8684BA"
yellow  = "#948CCB"
blue    = "#AF9BE2"
magenta = "#D6ABF8"
cyan    = "#CFB1F4"
white   = "#d6d9e3"

[colors.bright]
black   = "#95979e"
red     = "#7E80B6"
green   = "#8684BA"
yellow  = "#948CCB"
blue    = "#AF9BE2"
magenta = "#D6ABF8"
cyan    = "#CFB1F4"
white   = "#d6d9e3"

[font.normal]
family = "MesloLGS NF"
