[colors.primary]
background = "#071007"
foreground = "#c7e1e6"

[colors.cursor]
text = "#071007"
cursor = "#c7e1e6"

[colors.normal]
black   = "#071007"
red     = "#537BC2"
green   = "#5EA29F"
yellow  = "#6BB7A6"
blue    = "#659DCD"
magenta = "#9AD19F"
cyan    = "#89B5DB"
white   = "#c7e1e6"

[colors.bright]
black   = "#8b9da1"
red     = "#537BC2"
green   = "#5EA29F"
yellow  = "#6BB7A6"
blue    = "#659DCD"
magenta = "#9AD19F"
cyan    = "#89B5DB"
white   = "#c7e1e6"

[font.normal]
family = "MesloLGS NF"
