[colors.primary]
background = "#271318"
foreground = "#dbc6e1"

[colors.cursor]
text = "#271318"
cursor = "#dbc6e1"

[colors.normal]
black   = "#271318"
red     = "#E68D74"
green   = "#E9A663"
yellow  = "#EFC072"
blue    = "#B36CA7"
magenta = "#E1A08B"
cyan    = "#F8D3A0"
white   = "#dbc6e1"

[colors.bright]
black   = "#998a9d"
red     = "#E68D74"
green   = "#E9A663"
yellow  = "#EFC072"
blue    = "#B36CA7"
magenta = "#E1A08B"
cyan    = "#F8D3A0"
white   = "#dbc6e1"
