[colors.primary]
background = "#2e2328"
foreground = "#ddcfd8"

[colors.cursor]
text = "#2e2328"
cursor = "#ddcfd8"

[colors.normal]
black   = "#2e2328"
red     = "#A85DAF"
green   = "#E55F9C"
yellow  = "#758E97"
blue    = "#49D1D3"
magenta = "#9C9BA6"
cyan    = "#D397AB"
white   = "#ddcfd8"

[colors.bright]
black   = "#9a9097"
red     = "#A85DAF"
green   = "#E55F9C"
yellow  = "#758E97"
blue    = "#49D1D3"
magenta = "#9C9BA6"
cyan    = "#D397AB"
white   = "#ddcfd8"

[font]
size = 7.5

[font.normal]
family = "MesloLGS NF"
