[Desktop Entry]
Type=X-GNOME-Metatheme
Name=my-wal-theme-paisaje-3
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=my-wal-theme-paisaje-3
GtkTheme=my-wal-theme-paisaje-3
IconTheme=my-wal-theme-paisaje-3
MetacityTheme=my-wal-theme-paisaje-3
