[colors.primary]
background = "#0a101a"
foreground = "#f5dddf"

[colors.cursor]
text = "#0a101a"
cursor = "#f5dddf"

[colors.normal]
black   = "#0a101a"
red     = "#607788"
green   = "#BC7888"
yellow  = "#60A49F"
blue    = "#A28C97"
magenta = "#E599A4"
cyan    = "#D7C6C9"
white   = "#f5dddf"

[colors.bright]
black   = "#ab9a9c"
red     = "#607788"
green   = "#BC7888"
yellow  = "#60A49F"
blue    = "#A28C97"
magenta = "#E599A4"
cyan    = "#D7C6C9"
white   = "#f5dddf"

[font.normal]
family = "MesloLGS NF"
