[colors.primary]
background = "#03142D"
foreground = "#d7d2ce"

[colors.cursor]
text = "#03142D"
cursor = "#d7d2ce"

[colors.normal]
black   = "#03142D"
red     = "#EBB079"
green   = "#1F6E8B"
yellow  = "#5F7189"
blue    = "#2D94A7"
magenta = "#5AA5B1"
cyan    = "#5ABDC8"
white   = "#d7d2ce"

[colors.bright]
black   = "#969390"
red     = "#EBB079"
green   = "#1F6E8B"
yellow  = "#5F7189"
blue    = "#2D94A7"
magenta = "#5AA5B1"
cyan    = "#5ABDC8"
white   = "#d7d2ce"
