[colors.primary]
background = "#352830"
foreground = "#f6dbf5"

[colors.cursor]
text = "#352830"
cursor = "#f6dbf5"

[colors.normal]
black   = "#352830"
red     = "#EA6C8D"
green   = "#588BD0"
yellow  = "#B4A6AC"
blue    = "#E3ADA9"
magenta = "#E8C8B8"
cyan    = "#E8D3CE"
white   = "#f6dbf5"

[colors.bright]
black   = "#ac99ab"
red     = "#EA6C8D"
green   = "#588BD0"
yellow  = "#B4A6AC"
blue    = "#E3ADA9"
magenta = "#E8C8B8"
cyan    = "#E8D3CE"
white   = "#f6dbf5"

[font.normal]
family = "MesloLGS NF"
