[colors.primary]
background = "#181139"
foreground = "#e5c7cd"

[colors.cursor]
text = "#181139"
cursor = "#e5c7cd"

[colors.normal]
black   = "#181139"
red     = "#57489C"
green   = "#60569E"
yellow  = "#9A6891"
blue    = "#A077BF"
magenta = "#94899A"
cyan    = "#AF98AF"
white   = "#e5c7cd"

[colors.bright]
black   = "#a08b8f"
red     = "#57489C"
green   = "#60569E"
yellow  = "#9A6891"
blue    = "#A077BF"
magenta = "#94899A"
cyan    = "#AF98AF"
white   = "#e5c7cd"

[font.normal]
family = "MesloLGS NF"
