foreground   #f2e2c6
background   #17191b
cursor       #f2e2c6

color0       #17191b
color8       #a99e8a
color1       #BE9368
color9       #BE9368
color2       #F0946D
color10      #F0946D
color3       #9E7D81
color11      #9E7D81
color4       #AF9091
color12      #AF9091
color5       #E2AA9F
color13      #E2AA9F
color6       #D2ABAA
color14      #D2ABAA
color7       #f2e2c6
color15      #f2e2c6
