[colors.primary]
background = "#150e10"
foreground = "#f2e1cd"

[colors.cursor]
text = "#150e10"
cursor = "#f2e1cd"

[colors.normal]
black   = "#150e10"
red     = "#9D665A"
green   = "#BF906C"
yellow  = "#D69571"
blue    = "#847D82"
magenta = "#BA8D84"
cyan    = "#DAA58F"
white   = "#f2e1cd"

[colors.bright]
black   = "#a99d8f"
red     = "#9D665A"
green   = "#BF906C"
yellow  = "#D69571"
blue    = "#847D82"
magenta = "#BA8D84"
cyan    = "#DAA58F"
white   = "#f2e1cd"

[font.normal]
family = "MesloLGS NF"
