[colors.primary]
background = "#0A0F19"
foreground = "#ead2da"

[colors.cursor]
text = "#0A0F19"
cursor = "#ead2da"

[colors.normal]
black   = "#0A0F19"
red     = "#61738E"
green   = "#997691"
yellow  = "#C57A96"
blue    = "#6B88A4"
magenta = "#A590A8"
cyan    = "#D49BB1"
white   = "#ead2da"

[colors.bright]
black   = "#a39398"
red     = "#61738E"
green   = "#997691"
yellow  = "#C57A96"
blue    = "#6B88A4"
magenta = "#A590A8"
cyan    = "#D49BB1"
white   = "#ead2da"

[font.normal]
family = "MesloLGS NF"
