foreground   #e9c0c8
background   #1e0913
cursor       #e9c0c8

color0       #1e0913
color8       #a3868c
color1       #CB5E78
color9       #CB5E78
color2       #C88F74
color10      #C88F74
color3       #B76589
color11      #B76589
color4       #CE728C
color12      #CE728C
color5       #DA6F92
color13      #DA6F92
color6       #CB64B7
color14      #CB64B7
color7       #e9c0c8
color15      #e9c0c8
