foreground   #efcacb
background   #14060e
cursor       #efcacb

color0       #14060e
color8       #a78d8e
color1       #AC5B6C
color9       #AC5B6C
color2       #CC6975
color10      #CC6975
color3       #BD6F81
color11      #BD6F81
color4       #D07884
color12      #D07884
color5       #D7888F
color13      #D7888F
color6       #E99296
color14      #E99296
color7       #efcacb
color15      #efcacb
