[colors.primary]
background = "#172431"
foreground = "#ece3eb"

[colors.cursor]
text = "#172431"
cursor = "#ece3eb"

[colors.normal]
black   = "#172431"
red     = "#5293B0"
green   = "#658DA0"
yellow  = "#9D9BAA"
blue    = "#ABB5CC"
magenta = "#C5BFCD"
cyan    = "#D6D1DF"
white   = "#ece3eb"

[colors.bright]
black   = "#a59ea4"
red     = "#5293B0"
green   = "#658DA0"
yellow  = "#9D9BAA"
blue    = "#ABB5CC"
magenta = "#C5BFCD"
cyan    = "#D6D1DF"
white   = "#ece3eb"
