foreground   #ead2da
background   #0A0F19
cursor       #ead2da

color0       #0A0F19
color8       #a39398
color1       #61738E
color9       #61738E
color2       #997691
color10      #997691
color3       #C57A96
color11      #C57A96
color4       #6B88A4
color12      #6B88A4
color5       #A590A8
color13      #A590A8
color6       #D49BB1
color14      #D49BB1
color7       #ead2da
color15      #ead2da
