[colors.primary]
background = "#181013"
foreground = "#e4d6cc"

[colors.cursor]
text = "#181013"
cursor = "#e4d6cc"

[colors.normal]
black   = "#181013"
red     = "#A04B36"
green   = "#9B6351"
yellow  = "#897A74"
blue    = "#C64950"
magenta = "#C39B60"
cyan    = "#9F9EA5"
white   = "#e4d6cc"

[colors.bright]
black   = "#9f958e"
red     = "#A04B36"
green   = "#9B6351"
yellow  = "#897A74"
blue    = "#C64950"
magenta = "#C39B60"
cyan    = "#9F9EA5"
white   = "#e4d6cc"
