[colors.primary]
background = "#031D2D"
foreground = "#8edce4"

[colors.cursor]
text = "#031D2D"
cursor = "#8edce4"

[colors.normal]
black   = "#031D2D"
red     = "#127496"
green   = "#178EB1"
yellow  = "#18A1A4"
blue    = "#4BBCAE"
magenta = "#2CC5B6"
cyan    = "#1EA9D0"
white   = "#8edce4"

[colors.bright]
black   = "#639a9f"
red     = "#127496"
green   = "#178EB1"
yellow  = "#18A1A4"
blue    = "#4BBCAE"
magenta = "#2CC5B6"
cyan    = "#1EA9D0"
white   = "#8edce4"

[font.normal]
family = "MesloLGS NF"
